services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress:/var/www/html/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      args:
        CERT_FOLDER: ${CERT_FOLDER}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${COMMON_NAME}
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/html/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress

  website:
    build:
      context: ./requirements/bonus/portfolio/
    container_name: portfolio
    ports:
      - '8080:3000'
    restart: on-failure

  adminer:
    container_name: Adminer
    build:
      context: ./requirements/bonus/Adminer/
    ports:
      - "8081:8080"
    networks:
      - all
    init: true
    restart: on-failure
    depends_on:
      - mariadb

  redis:
    container_name: Redis
    build:
      context: ./requirements/bonus/Redis/
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - all
    init: true
    restart: on-failure

  ftp:
    container_name: FTP
    build: requirements/bonus/FTP/
    env_file:
      - .env
    ports:
      - "21:21"
    volumes:
      - wordpress:/var/www/html/
    networks:
      - all
    restart: on-failure
  
  cadvisor:
    container_name: cAdvisor
    build:
      context: ./requirements/bonus/cAdvisor/
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8084:8084"
    networks:
      - all
    restart: on-failure
 

volumes:

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress


  redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/redis

networks:
  all:
    driver: bridge